name: All the Docker Things

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Generate dat tag
        uses: paulhatch/semantic-version@v4.0.2
        with:
    # The prefix to use to identify tags
          tag_prefix: "v"
    # A string which, if present in a git commit, indicates that a change represents a
    # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
    # A string which indicates the flags used by the `major_pattern` regular expression. Supported flags: idgs
          major_regexp_flags: ""
    # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
    # A string which indicates the flags used by the `minor_pattern` regular expression. Supported flags: idgs
          minor_regexp_flags: ""
    # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}-prerelease${increment}"
  
      
      
      - 
        name: Build and Yeet to Docker Hub
  # You may pin to the exact commit or the version.
  # uses: zenato/docker-action@8309ea4d790d074676660449b9f2bcbcae25cdb9
        uses: zenato/docker-action@v1.0.0
        with:
    # Registry username
          username: ${{ secrets.DOCKER_USER }}
    # Registry password
          password: ${{ secrets.DOCKER_PASSWORD }}
    # Repository on registry
          repository: theboatymcboatface/flame
    # Registry hostname
         # registry: # optional
    # Image tag
          tag: ${{ INPUT_version_tag }}
      
